# Generated by Django 3.1.7 on 2021-05-02 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210502_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofileevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 40, 22, 148537)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 40, 22, 147540)),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 40, 22, 148537)),
        ),
        migrations.AlterField(
            model_name='logoutevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 40, 22, 148537)),
        ),
        migrations.AlterField(
            model_name='registerevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 40, 22, 148537)),
        ),
        migrations.AlterField(
            model_name='viewpageevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 40, 22, 148537)),
        ),
    ]
