# Generated by Django 3.1.7 on 2021-05-02 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210502_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('stats', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 50, 3, 401529))),
            ],
        ),
        migrations.AlterField(
            model_name='editprofileevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 50, 3, 402525)),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 50, 3, 401529)),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 50, 3, 402525)),
        ),
        migrations.AlterField(
            model_name='logoutevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 50, 3, 402525)),
        ),
        migrations.AlterField(
            model_name='registerevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 50, 3, 402525)),
        ),
        migrations.AlterField(
            model_name='viewpageevent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 18, 50, 3, 402525)),
        ),
    ]
